---
- name: install arch linux
  hosts: localhost
  vars:
    idea_image: "draducanu/arch-idea"
    idea_container: "idea-container"
    build: true
  tasks:
    - name: build idea image
      docker_image:
        name: "{{idea_image}}"
        source: build
        push: yes
        force_source: true
        build:
          rm: no
          pull: no
          path: "./Archlinux-idea"
          args:
            IDEA_VERSION: 2019.3.4-no-jbr
      when: "build == true"

    - name: open idea
      docker_container:
        name: "{{idea_container}}"
        image: "{{idea_image}}"
        pull: true
        env:
          DISPLAY: ":0"
        volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix
          - ~/IdeaProjects:/root/IdeaProjects
          - ~/.IntelliJIdea2019.3:/root/.IntelliJIdea2019.3
          - ~/libs:/root/libs
          - ~/.m2:/root/.m2
          - ~/.gradle:/root/.gradle
          - ~/.local/share/JetBrains:/root/.local/share/JetBrains
          - ~/.java/.userPrefs/jetbrains:/root/.java/.userPrefs/jetbrains
