---
- name: install arch linux
  hosts: localhost
  vars:
    idea_image: "draducanu/arch-idea"
    idea_container: "idea-container"
  tasks:
    - name: build idea image
      docker_image:
        name: "{{idea_image}}"
        source: build
        push: yes
        force_source: true
        build:
          rm: no
          pull: no
          path: "./Archlinux-idea"
          args:
            IDEA_VERSION: 2019.3.3-no-jbr

    - name: open idea
      docker_container:
        name: "{{idea_container}}"
        image: "{{idea_image}}"
        pull: true
        env:
          DISPLAY: ":0"
        volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix
          - ~/IdeaProjects:/home/developer/IdeaProjects
          - ~/IdeaProjects/libs:/home/developer/libs
