---
- name: install arch linux
  hosts: localhost
  vars:
    image_name: "idea-image-flutter"
    image_container: "idea-container-flutter"
  tasks:
    - name: build image
      docker_image:
        name: "{{image_name}}"
        source: build
        rm: no
        force_source: yes
        build:
          pull: no
          path: "./Archlinux-idea-flutter"
          args:
            FLUTTER_VERSION: v1.12.13+hotfix.8-stable


    - name: open idea
      docker_container:
        name: "{{image_container}}"
        image: "{{image_name}}"
        pull: false
        env:
          DISPLAY: ":0"
        volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix
          - ~/IdeaProjects:/home/developer/IdeaProjects
          - ~/IdeaProjects/idea-settings:/home/developer/.IntelliJIdea2019.2
